paths:
  input_dir: data/raw
  output_dir: data/processed

classification:
  categories:
    - invoice
    - contract
    - financial_report
    - client_info
    - other
  model: ""

duplicates:
  content_hash: ""
  simhash_bits: 
  minhash_perm: 
  cosine_threshold: 
